image:
  file: .gitpod.Dockerfile
  
ports:
  - port: 8080
    onOpen: open-preview
  - port: 8000
    onOpen: open-preview
  - port: 9009
    onOpen: ignore

tasks:
  - init: bash bash/init-gitpod.sh && url=$(gp url 8000); sed -i'' "s#^APP_URL=http://localhost*#APP_URL=$url\nASSET_URL=$url#g" .env
  - command: php artisan serve && gp await-port 8000
    openMode: split-left
    
vscode:
  extensions:
    - felixfbecker.php-debug@1.14.5:xEr6zDqY853IE2HQtLtXPA==
