image:
  file: .gitpod.Dockerfile
  
ports:
  - port: 8080
    onOpen: open-preview
  - port: 8000
    onOpen: open-preview
  - port: 9009
    onOpen: ignore

tasks:
  - init: |
      bash bash/init-gitpod.sh \
      && source ~/.bash_profile \
      && url=$(gp url 8000); sed -i'' "s#^APP_URL=http://localhost*#APP_URL=$url\nASSET_URL=$url#g" .env
  - command: |
      clear && sleep 1 \
      && php -S 127.0.0.1:8000 -t public/ \
      && gp await-port 8000 \
      && sleep 5 \
      && gp preview $(gp url 8000)
    openMode: split-left
    
vscode:
  extensions:
    - felixfbecker.php-debug@1.14.5:xEr6zDqY853IE2HQtLtXPA==
