image:
  file: .gitpod.Dockerfile
  
ports:
  - port: 8080
    onOpen: open-preview
  - port: 8000
    onOpen: ignore
  - port: 9009
    onOpen: ignore
  - port: 3306
    onOpen: ignore

tasks:
  - init: |
      . bash/third-party/spinner.sh &&
      start_spinner "Initializing MySql..." &&
      gp await-port 3306 &&
      stop_spinner $? &&
      bash bash/init-gitpod.sh &&
      source ~/.bash_profile &&
      url=$(gp url 8000); sed -i'' "s#^APP_URL=http://localhost*#APP_URL=$url\nASSET_URL=$url#g" .env
  - OpenMode: split-right
    command: |
      gp await-port 3306 &&
      php -S 127.0.0.1:8000 -t public/
    name: PHP dev server
  - openMode: split-left
    command: |
      gp await-port 8000 &&
      gp preview "$(gp url 8000)?firstrun=1" &&
      echo "Auto refreshing preview browser. Please wait 5 seconds."
      sleep 5 && gp preview $(gp url 8000) &&
      echo "Preview browser is open"
    name: Main Terminal

vscode:
  extensions:
    - felixfbecker.php-debug@1.14.5:xEr6zDqY853IE2HQtLtXPA==
