image:
  file: .gitpod.Dockerfile
  
ports:
  - port: 8080
    onOpen: open-preview
  - port: 8000
    onOpen: open-preview
  - port: 9009
    onOpen: ignore
  - port: 3306
    onOpen: ignore

tasks:
  - before: echo "Starting up..."
  - init: |
      bash bash/init-gitpod.sh \
      && source ~/.bash_profile \
      && url=$(gp url 8000); sed -i'' "s#^APP_URL=http://localhost*#APP_URL=$url\nASSET_URL=$url#g" .env
  - command: |
      echo "Starting up debugable web server..."
      sleep 5 && bash bash/commands/start-debugable-php.sh
    openMode: split-right
    
vscode:
  extensions:
    - felixfbecker.php-debug@1.14.5:xEr6zDqY853IE2HQtLtXPA==
